resolver: lts-18.16
packages:
- .

extra-deps:
- github: NorfairKing/dirforest
  commit: 69e8ae036b047fae105c1fe990e175a7572a3eba
  subdirs:
    - dirforest
    - genvalidity-dirforest
nix:
  packages:
    - zlib
    - haskellPackages.autoexporter
